---
services:
  avalanche:
    image: "quay.io/freshtracks.io/avalanche"
    container_name: "aval"
    restart: always
    command:
      - "--metric-count=1000"
      - "--series-count=50"
    networks:
      lan:
    ports:
      - 9001:9001


  prom:
    image: "prom/prometheus:latest"
    container_name: "prom"
    restart: always
    networks:
      lan:
    volumes:
      - ./prom/:/etc/prometheus/
    ports:
      - 9090:9090

  alert:
    image: "prom/alertmanager:latest"
    container_name: "alert"
    restart: always
    networks:
      lan:
    volumes:
      - ./alert/:/etc/alertmanager/
    ports:
      - 9093:9093

  grafa:
    image: "grafana/grafana-enterprise:latest"
    container_name: "grafa"
    restart: always
    networks:
      lan:
    volumes:
      - ./grafa/grafana.ini:/etc/grafana/grafana.ini
      - ./grafa/prom.yml:/etc/grafana/provisioning/datasources/prom.yml
      - 'grafana:/var/lib/grafana'
    ports:
      - 3000:3000

  proxy:
    image: "nginx:latest"
    container_name: "proxy"
    restart: always
    networks:
      lan:
      wan:
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8080:8080

  influx:
    image: "influxdb:1.8"
    container_name: "influx"
    restart: always
    networks:
      lan:
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_USER=prometheus
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Pa$$w0rd
    volumes:
      - 'influxdb:/var/lib/influxdb'
    ports:
      - 8086:8086

  client:
    image: quay.io/prometheus/node-exporter:latest
    container_name: "docker_client"
    restart: always
    networks:
      lan:
    ports:
      - 9100:9100


networks:
  lan:
  wan:

volumes:
  influxdb:
  grafana:
