---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "prometheus"
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: "prometheus"
  template:
    metadata:
      labels:
        app: "prometheus"
    spec:
      containers:
        - name: "prometheus"
          image: "prometheus:latest"
          imagePullPolicy: Never
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.config.file=/etc/prometheus/web.yml'
            - '--web.external-url=http://prometheus.cld.education'
            - '--storage.tsdb.retention=12h'
            - '--storage.tsdb.path=/prometheus'
          ports:
            - name: http
              containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: "prometheus"
spec:
  selector:
    app: "prometheus"
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31001
