apiVersion: apps/v1
kind: Deployment
metadata:
  name: "grafana"
spec:
  selector:
    matchLabels:
      app: "grafana"
  template:
    metadata:
      labels:
        app: "grafana"
    spec:
      containers:
        - name: "grafana"
          image: "grafana:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: "grafana"
spec:
  selector:
    app: "grafana"
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31004