apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: direct
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prom:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.49.1
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m

