global:
  scrape_interval: 10s

rule_files:
  - "rules.yml"
  # - "second_rules.yml"

scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090

 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100