---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  labels:
    name: grafana-conf
data:
  grafana.ini: |-
    [paths]
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [server]
    protocol = http
    root_url = http://mydomain.com:81/grafana/
    serve_from_sub_path = true
    
    [security]
    admin_user = admin
    admin_password = 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    name: grafana-datasource
data: 
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: direct
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://prometheus:9090
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.49.1
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m


