---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "prometheus"
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: "prometheus"
  template:
    metadata:
      labels:
        app: "prometheus"
    spec:
      containers:
        - name: "prometheus"
          image: "prom/prometheus:latest"
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.config.file=/etc/prometheus/web.yml'
            - '--web.external-url=http://mydomain.com:81/prometheus'
            - '--storage.tsdb.retention=12h'
            - '--storage.tsdb.path=/prometheus'
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}
---          
apiVersion: v1
kind: Service
metadata:
  name: "prometheus"
spec:
  selector:
    app: "prometheus"
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31001
